name: "Add Issue to Org Project"
on:
  issues:
    types: [opened, labeled]

jobs:
  add:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Add issue to project via GraphQL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          script: |
            const projectNumber = 3; // 追加先Project番号
            const org = 'YOUR_ORG';
            const issueId = context.payload.issue.node_id;

            const { organization } = await github.graphql(`
              query($org: String!, $number: Int!) {
                organization(login: $org) {
                  projectV2(number: $number) { id }
                }
              }`, { org, number: projectNumber });

            const projectId = organization.projectV2.id;

            await github.graphql(`
              mutation($project: ID!, $content: ID!) {
                addProjectV2ItemById(input: {projectId: $project, contentId: $content}) {
                  item { id }
                }
              }`, { project: projectId, content: issueId });
